---
abstract: unknown
author:
  - 'Craig Scrivner <scrivner@geology.cwu.edu>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.04, CPAN::Meta::Converter version 2.150001'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Seismogram
no_index:
  directory:
    - t
    - inc
requires:
  Test::More: '0'
version: '1.02'
